import fs from 'fs';
import path from 'path';
import url from 'url';

const __dirname = path.dirname(url.fileURLToPath(import.meta.url));
const colorsPath = path.join(__dirname, '..', 'src', 'Colors.js');

async function loadColors() {
  // import the current module dynamically
  const mod = await import(url.pathToFileURL(colorsPath) + `?update=${Date.now()}`);
  return mod.default;
}

function computeHslComplementary(hsl) {
  if (!hsl || typeof hsl.h !== 'number') return null;
  return { h: (hsl.h + 180) % 360, s: hsl.s, l: 100 - hsl.l };
}

function hslToHex(h, s, l) {
  s /= 100;
  l /= 100;
  const c = (1 - Math.abs(2 * l - 1)) * s;
  const hh = h / 60;
  const x = c * (1 - Math.abs((hh % 2) - 1));
  let r = 0, g = 0, b = 0;
  if (0 <= hh && hh < 1) { r = c; g = x; b = 0; }
  else if (1 <= hh && hh < 2) { r = x; g = c; b = 0; }
  else if (2 <= hh && hh < 3) { r = 0; g = c; b = x; }
  else if (3 <= hh && hh < 4) { r = 0; g = x; b = c; }
  else if (4 <= hh && hh < 5) { r = x; g = 0; b = c; }
  else { r = c; g = 0; b = x; }
  const m = l - c / 2;
  const toHex = (v) => Math.round((v + m) * 255).toString(16).padStart(2, '0').toUpperCase();
  return `#${toHex(r)}${toHex(g)}${toHex(b)}`;
}

function invertHex(hex) {
  const h = hex.replace('#', '');
  if (h.length !== 6) return hex.toUpperCase();
  const r = 255 - parseInt(h.substring(0,2), 16);
  const g = 255 - parseInt(h.substring(2,4), 16);
  const b = 255 - parseInt(h.substring(4,6), 16);
  return `#${[r,g,b].map(v=>v.toString(16).padStart(2,'0')).join('').toUpperCase()}`;
}

function toJs(value, indent = 2) {
  const pad = (n) => ' '.repeat(n);
  function inner(v, level) {
    if (v === null) return 'null';
    if (Array.isArray(v)) {
      if (v.length === 0) return '[]';
      const items = v.map(i => inner(i, level + indent)).join(',\n');
      return `[\n${pad(level+indent)}${items.replace(/\n/g, '\n' + pad(level+indent))}\n${pad(level)}]`;
    }
    if (typeof v === 'object') {
      const keys = Object.keys(v);
      if (keys.length === 0) return '{}';
      const parts = keys.map(k => `${k}: ${inner(v[k], level + indent)}`);
      return `{\n${pad(level+indent)}${parts.join(',\n' + pad(level+indent))}\n${pad(level)}}`;
    }
    if (typeof v === 'string') return JSON.stringify(v);
    return String(v);
  }
  return inner(value, 0);
}

(async function main(){
  const Colors = await loadColors();
  const updated = Colors.map(color => {
    const base = { ...color };
    const comp = computeHslComplementary(base.hsl);
    if (comp) {
      base.hslComplementary = { h: Number(comp.h), s: Number(comp.s), l: Number(comp.l) };
      base.hexComplementary = hslToHex(comp.h, comp.s, comp.l);
    } else if (base.code) {
      base.hexComplementary = invertHex(base.code);
    }
    return base;
  });

  const header = `// This file was autogenerated by scripts/fix_colors.mjs\n// It contains the Colors dataset with recomputed complementary values.\n\n`;
  const body = `const Colors = ${toJs(updated, 2)};\n\nexport default Colors;\n`;
  const out = header + body;
  fs.writeFileSync(colorsPath, out, 'utf8');
  console.log('Wrote', colorsPath);
})();
